apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 
  annotations:
    
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: app1.com
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80