global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: "nginx"
  hosts:
    domain: 192.168.42.110.nip.io
    externalIP: 192.168.42.110
    https: false
  # Disable Rails bootsnap cache (temporary)
  rails:
    bootsnap:
      enabled: false
  shell:
    # Configure the clone link in the UI to include the high-numbered NodePort
    # value from below (`gitlab.gitlab-shell.service.nodePort`)
    port: 31337
# Don't use certmanager, we'll self-sign
certmanager:
  install: false
nginx-ingress:
  enabled: false
# Save resources
prometheus:
  install: false
gitlab-runner:
  install: false
grafana:
    enabled: false
spamcheck:
    enabled: false

# Reduce replica counts, reducing CPU & memory requirements
gitlab:
  webservice:
    resources:
      requests:
        memory: 2G
    minReplicas: 1
    maxReplicas: 1
    puma:
      threads:
        min: 1
        max: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    concurrency: 10
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    # Map gitlab-shell to a high-numbered NodePort to support cloning over SSH since
    # Minikube takes port 22.
    service:
      type: NodePort
      nodePort: 31337
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1

