server_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.define "alzaynouS" do |master_config|
    master_config.vm.hostname = "alzaynouS"
    worker_config.vm.synced_folder "./confs", "/confs"
    master_config.vm.network  "private_network" , ip: server_ip
    master_config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "alzaynouS"
    end
   master_config.vm.provision "shell", path: './server_script.sh'
  end

end