server_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "alzaynouS" do |master_config|
    master_config.vm.hostname = "alzaynouS"
    master_config.vm.synced_folder "./confs", "/confs"
    master_config.vm.network  "private_network" , ip: server_ip
    master_config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      v.name = "alzaynouS"
    end
   master_config.vm.provision "shell", path: './scripts/install.sh', privileged: false
   master_config.vm.provision "shell", path: './scripts/config.sh', privileged: false
  end

end