server_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "alzaynou" do |master_config|
    master_config.vm.hostname = "alzaynou"
    master_config.vm.synced_folder "./", "/confs"
    master_config.vm.network  "private_network" , ip: server_ip
    master_config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
      v.name = "alzaynou"
    end
  end
end